all:
	cp *.ipynb                ../assets/notebooks/
	cp thevenincircuit.svg    ../assets/img
	cp rcvdividers.svg        ../assets/img
	cp rlcparallel.svg        ../assets/img
	cp rlcparallelreal.svg    ../assets/img
	cp diodevdivider.svg      ../assets/img
	cp bridgerectifier.svg    ../assets/img
	cp ebersmollcircuit.svg   ../assets/img
	cp commonemitter.svg      ../assets/img
	cp amradiolabels.svg      ../assets/img
	cp loopstick.svg          ../assets/img
	cp rlccircuit.svg         ../assets/img
	cp rlctuner.svg           ../assets/img
	cp demodulatortest.svg    ../assets/img
	cp lm386.svg              ../assets/img
	cp amradio.svg            ../assets/img
	cp amradio_components.png ../assets/img
	echo "Labs : done."

