all:
	cp thevenincircuit.svg    ../assets/img
	cp rcvdividers.svg        ../assets/img
	cp rlcparallel.svg        ../assets/img
	cp rlcparallelreal.svg    ../assets/img
	cp diodevdivider.svg      ../assets/img
	cp ebersmollcircuit.svg   ../assets/img
	cp commonemitter.svg      ../assets/img
	cp rlccircuit.svg         ../assets/img
	echo "Labs : done."

